# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\")\n\x0bSimpleReply\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x1d\n\rSimpleRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"5\n\tDataReply\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\")\n\x0b\x44\x61taRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\x87\x01\n\x0b\x66ileService\x12&\n\x06Upload\x12\x0c.DataRequest\x1a\x0c.SimpleReply\"\x00\x12(\n\x08\x44ownload\x12\x0e.SimpleRequest\x1a\n.DataReply\"\x00\x12&\n\x06Update\x12\x0c.DataRequest\x1a\x0c.SimpleReply\"\x00\x32p\n\x10\x64irectoryService\x12/\n\rGetFileServer\x12\x0e.SimpleRequest\x1a\x0c.SimpleReply\"\x00\x12+\n\tGetSlaves\x12\x0e.SimpleRequest\x1a\x0c.SimpleReply\"\x00\x32_\n\x0blockService\x12&\n\x04Lock\x12\x0e.SimpleRequest\x1a\x0c.SimpleReply\"\x00\x12(\n\x06Unlock\x12\x0e.SimpleRequest\x1a\x0c.SimpleReply\"\x00\x62\x06proto3')
)




_SIMPLEREPLY = _descriptor.Descriptor(
  name='SimpleReply',
  full_name='SimpleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='SimpleReply.flag', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='SimpleReply.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=58,
)


_SIMPLEREQUEST = _descriptor.Descriptor(
  name='SimpleRequest',
  full_name='SimpleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='SimpleRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=89,
)


_DATAREPLY = _descriptor.Descriptor(
  name='DataReply',
  full_name='DataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='DataReply.flag', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='DataReply.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='DataReply.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=144,
)


_DATAREQUEST = _descriptor.Descriptor(
  name='DataRequest',
  full_name='DataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='DataRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='DataRequest.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['SimpleReply'] = _SIMPLEREPLY
DESCRIPTOR.message_types_by_name['SimpleRequest'] = _SIMPLEREQUEST
DESCRIPTOR.message_types_by_name['DataReply'] = _DATAREPLY
DESCRIPTOR.message_types_by_name['DataRequest'] = _DATAREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleReply = _reflection.GeneratedProtocolMessageType('SimpleReply', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:SimpleReply)
  })
_sym_db.RegisterMessage(SimpleReply)

SimpleRequest = _reflection.GeneratedProtocolMessageType('SimpleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:SimpleRequest)
  })
_sym_db.RegisterMessage(SimpleRequest)

DataReply = _reflection.GeneratedProtocolMessageType('DataReply', (_message.Message,), {
  'DESCRIPTOR' : _DATAREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:DataReply)
  })
_sym_db.RegisterMessage(DataReply)

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:DataRequest)
  })
_sym_db.RegisterMessage(DataRequest)



_FILESERVICE = _descriptor.ServiceDescriptor(
  name='fileService',
  full_name='fileService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=190,
  serialized_end=325,
  methods=[
  _descriptor.MethodDescriptor(
    name='Upload',
    full_name='fileService.Upload',
    index=0,
    containing_service=None,
    input_type=_DATAREQUEST,
    output_type=_SIMPLEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Download',
    full_name='fileService.Download',
    index=1,
    containing_service=None,
    input_type=_SIMPLEREQUEST,
    output_type=_DATAREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='fileService.Update',
    index=2,
    containing_service=None,
    input_type=_DATAREQUEST,
    output_type=_SIMPLEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESERVICE)

DESCRIPTOR.services_by_name['fileService'] = _FILESERVICE


_DIRECTORYSERVICE = _descriptor.ServiceDescriptor(
  name='directoryService',
  full_name='directoryService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=327,
  serialized_end=439,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFileServer',
    full_name='directoryService.GetFileServer',
    index=0,
    containing_service=None,
    input_type=_SIMPLEREQUEST,
    output_type=_SIMPLEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSlaves',
    full_name='directoryService.GetSlaves',
    index=1,
    containing_service=None,
    input_type=_SIMPLEREQUEST,
    output_type=_SIMPLEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIRECTORYSERVICE)

DESCRIPTOR.services_by_name['directoryService'] = _DIRECTORYSERVICE


_LOCKSERVICE = _descriptor.ServiceDescriptor(
  name='lockService',
  full_name='lockService',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=441,
  serialized_end=536,
  methods=[
  _descriptor.MethodDescriptor(
    name='Lock',
    full_name='lockService.Lock',
    index=0,
    containing_service=None,
    input_type=_SIMPLEREQUEST,
    output_type=_SIMPLEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Unlock',
    full_name='lockService.Unlock',
    index=1,
    containing_service=None,
    input_type=_SIMPLEREQUEST,
    output_type=_SIMPLEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCKSERVICE)

DESCRIPTOR.services_by_name['lockService'] = _LOCKSERVICE

# @@protoc_insertion_point(module_scope)
